apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agri-app
  namespace: agri-dev
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: agri-app
  namespaceSelector:
    matchNames:
      - agri-dev
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
