replicaCount: 2
image:
  repository: xushnudbek-prog/agriculture-app
  tag: "0975668"
  pullPolicy: IfNotPresent
  registry: ghcr.io
service:
  type: NodePort
  port: 8080
  targetPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 512Mi
probes:
  readinessPath: /actuator/health/readiness
  livenessPath: /actuator/health/liveness
