replicaCount: 2
image:
  repository: xushnudbek-prog/agriculture-app
  tag: '5236688'
  pullPolicy: IfNotPresent
  registry: ghcr.io
service:
  type: NodePort
  port: 8080
  targetPort: 8080
resources:
  limits:
    cpu: 50m
    memory: 65Mi
  requests:
    cpu: 100m
    memory: 256Mi
probes:
  readinessPath: /actuator/health/readiness
  livenessPath: /actuator/health/liveness
