apiVersion: v1
kind: Service

metadata:
  name: agri-app
  namespace: agri-dev
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "{{ .Values.service.port }}"

spec:
  type: {{ .Values.service.type }}
  selector:
    app: agri-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}